2019-10-10 16:43:36,573 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 09:54:13,153 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 10:40:02,008 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 10:44:30,735 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 10:58:56,392 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 10:59:49,448 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 11:03:41,335 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 11:03:45,880 ERROR: Exception on /index [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 13, in index
    return render_template('index.html', title='Home', posts=posts)
NameError: name 'posts' is not defined
2019-10-11 11:03:50,149 ERROR: Exception on / [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 13, in index
    return render_template('index.html', title='Home', posts=posts)
NameError: name 'posts' is not defined
2019-10-11 11:03:54,772 ERROR: Exception on / [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 13, in index
    return render_template('index.html', title='Home', posts=posts)
NameError: name 'posts' is not defined
2019-10-11 11:04:17,724 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 11:04:20,887 ERROR: Exception on / [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 12, in index
    return render_template('index.html', title='Home', posts=posts)
NameError: name 'posts' is not defined
2019-10-11 11:04:23,519 ERROR: Exception on / [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 12, in index
    return render_template('index.html', title='Home', posts=posts)
NameError: name 'posts' is not defined
2019-10-11 11:05:12,016 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 11:15:14,315 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 11:16:48,157 INFO: Silvi startup [in C:\Users\sean\Documents\silvi\app\__init__.py:45]
2019-10-11 11:16:51,272 ERROR: Exception on /login [GET] [in c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sean\Documents\silvi\app\routes.py", line 18, in login
    form = LoginForm()
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\wtforms\form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\wtforms\form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\wtforms\meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\wtforms\fields\core.py", line 353, in bind
    return self.field_class(*self.args, **kw)
  File "c:\users\sean\documents\silvi\venv\lib\site-packages\wtforms\fields\core.py", line 702, in __init__
    super(BooleanField, self).__init__(label, validators, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'class_'
